### ISSUE TITLE
Update to 34.0?

### ISSUE THREAD

**Issue by romulasry** [nmeum/android-tools#103]
Build Tools, Revision 34.0.0 (February 2023)
https://developer.android.com/studio/releases/build-tools#notes

**Comment by Biswa96** [comment]
While redoing the patches for new release, I noticed that the @anatol's patch as not accepted here https://android-review.googlesource.com/c/platform/packages/modules/adb/+/2247053. Should it be kept?

**Comment by anatol** [comment]
> Should it be kept?

Please drop my patch. Upstream solved the problem in a slightly different way.

**Comment by Biswa96** [comment]
It's ironic to see it being fixed that way. In some repositories, maintainers suggest to fix the issue instead of suppressing the compiler warning/error with workaround 😔

**Comment by anatol** [comment]
Yeah, upstream decided just suppress the compiler warning. In this case (empty payload), it is fine. But if the message payload changes in the future, disabled warnings will make it harder to catch problems.

Anyway, upstream is going to maintain the code. Let them handle the situation then.

**Comment by Biswa96** [comment]
It seems that your patch is required for gcc. Here is the compiler error in archlinux

```c
/usr/include/linux/usbdevice_fs.h:134:41: error: flexible array member ‘usbdevfs_urb::iso_frame_desc’ not at end of ‘struct usb_handle’
  134 |         struct usbdevfs_iso_packet_desc iso_frame_desc[];
      |                                         ^~~~~~~~~~~~~~
```

**Comment by anatol** [comment]
I see. Could you please pull the upstream patch in this case?

**Comment by Biswa96** [comment]
Yeah, doing that exactly.

**Comment by Biswa96** [comment]
I have added a pull request to update to 34.0.0 version. Please build and test from the source tarball in CI artifact.

**Comment by anatol** [comment]
Thank you for your work @Biswa96. This patch has been published here https://github.com/nmeum/android-tools/releases/tag/34.0.0

Also upstream just cut a new 34.0.1 release:

```
34.0.1 (March 2023)
**adb**
macOS: Reverted "unstable connectivity (MacBook high speed cable)" resolution due to adb install hang (https://issuetracker.google.com/issues/270205252).
**fastboot**
Windows: Fixed "mke2fs: Illegal or malformed device name while trying to determine filesystem size" error introduced in Platform tools 34.0.0 (https://issuetracker.google.com/issues/271039230).
```

**Comment by Biswa96** [comment]
There is no separate platform-tools-34.0.1 tag in upstream. Wondering if those patches have to be added by distribution maintainers. Another way could be to apply those patches in CI before creating a tarball.

**Comment by anatol** [comment]
> There is no separate platform-tools-34.0.1 tag in upstream.

Android upstream regularly misses pushing these tags, unfortunately. It happened before, e.g. https://issuetracker.google.com/issues/229569602

I filed an upstream bug for missing 34.0.1 tag here https://issuetracker.google.com/issues/271591658

**Comment by anatol** [comment]
The 34.0.1 tag has been pushed to the repository. `android-tools` is now ready to move to this release. 

@Biswa96 I see you made recent 34.0.0 bump so it will be natural to take care of 34.0.1 release as well. Could you please take care of it?

**Comment by Biswa96** [comment]
OK, I'll look into it. Did the 34.0.1 change every submodules? For example,

* https://github.com/aosp-mirror/platform_system_core/tree/platform-tools-34.0.1
vs.
* https://github.com/aosp-mirror/platform_system_core/tree/platform-tools-34.0.0

I thought it will change only the adb and fastboot repositories.

**Comment by anatol** [comment]
Every android submodule is tagged with this new release. As of specific changes you need to look into `git diff` between these two tags.

**Comment by anatol** [comment]
Thank you @Biswa96 for your work!

**Comment by Biswa96** [comment]
anatol, could you ask for the new 36.0.0 tag in upstream, please?
