### ISSUE TITLE
Not working in fastboot mode, get stuck waiting for device

### ISSUE THREAD

**Issue by romulasry** [nmeum/android-tools#104]
adb reboot-bootloader
fastboot oem get_unlock_data
< waiting for any device >

and it stays here and doesn't work

**Comment by romulasry** [comment]
I tried unplugging and plugging in the cable, same issue.

**Comment by anatol** [comment]
Do you have up-to-date android udev files?

**Comment by romulasry** [comment]
https://src.fedoraproject.org/rpms/android-tools/blob/rawhide/f/51-android.rules

Is this up to date?

**Comment by romulasry** [comment]
lsusb
Bus 008 Device 062: ID 22b8:2e80 Motorola PCS Fastboot sofiap S

dmesg | tail -n 20
[ 9376.381111] usb 8-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 9376.381117] usb 8-2: Product: Fastboot sofiap S
[ 9376.381122] usb 8-2: Manufacturer: Motorola Mobility LLC.
[ 9376.381125] usb 8-2: SerialNumber: ZY22CDWFBS

**Comment by romulasry** [comment]
It seems to be in the package here: 

<pre class="syntaxhighlightblock"><code class="hljs ini">

#Motorola PCS
--
  | SUBSYSTEM=="usb", ATTR{idVendor}=="22b8", TAG+="systemd", ENV{SYSTEMD_WANTS}="adb.service"

</code></pre>

**Comment by vanaf** [comment]
> It seems to be in the package here: https://src.fedoraproject.org/rpms/android-tools/blob/rawhide/f/51-android.rules
> 
> ```
> 
> 
> #Motorola PCS
> --
>   | SUBSYSTEM=="usb", ATTR{idVendor}=="22b8", TAG+="systemd", ENV{SYSTEMD_WANTS}="adb.service"
> ```

This is only for adb.
If possible you can use sudo for fastboot operations I believe

**Comment by romulasry** [comment]
sudo fastboot works, still a bug though.

**Comment by Biswa96** [comment]
Has this issue been fixed with newer 34.0.5 release?

**Comment by romulasry** [comment]
> Has this issue been fixed with newer 34.0.5 release?

I don't know if I can test it I just got a new phone.

**Comment by Biswa96** [comment]
OK. Please feel free to reopen the issue when you see same issue.
