### ISSUE TITLE
Update to 30.0.4 (Android 11)

### ISSUE THREAD

**Issue by dashezup** [nmeum/android-tools#11]
platform-tools-30.0.4 is available now
https://android.googlesource.com/platform/system/core

One of the important feature of adb of this version is `adb pair` which available for Android 11+

[Connect to a device over Wi-Fi (Android 11+)](https://developer.android.com/studio/command-line/adb)

**Comment by nmeum** [comment]
I haven't had the time to update android-tools recently. I primarily use adb and fastboot for firmware updates and such things, thus I am not always highly motivated to keep this up to date. I will hopefully get to it eventually, it is just not on the top of my todo list at the moment.

**Comment by sgn** [comment]
FWIW, I'm working on it, I expect to finish in the next weekend (since I can only work on this in the weekend) https://github.com/sgn/android-tools/tree/android-tools-30.0.4

**Comment by nmeum** [comment]
https://github.com/nmeum/android-tools/releases/tag/30.0.5
