### ISSUE TITLE
Error: c++: error: unrecognized command-line option '-R'

### ISSUE THREAD

**Issue by XDream8** [nmeum/android-tools#116]
# Information
gcc: 13.1.0
musl: 1.2.4
cmake: 3.26.4

# short log
```sh
.
.
.
[100%] Linking CXX executable adb
c++: error: unrecognized command-line option '-R'
.
.
.
```

**Comment by Biswa96** [comment]
Are you compiling using git repository?

**Comment by XDream8** [comment]
No, I tried compiling using a source tarball from releses section(version 34.0.1).

**Comment by Biswa96** [comment]
Could you provide the Linux distribution information? I would like to reproduce the issue and have to use container images.

**Comment by XDream8** [comment]
Its [KISS-Linux](https://kisslinux.org/). An independent(currently community maintained) source based distribution. I dont think it has a container image tho.

**Comment by XDream8** [comment]
After I updated my system, it compiled successfully.

It seems to be [related to brotli](https://codeberg.org/kiss-community/community/commit/7c76ccdcd1d2a18e3e144e7f45483dc0b1b40b65).
## updated packages
- git
- python
- python-markupsafe
- hwdata
- brotli

**Comment by XDream8** [comment]
Closing the issue!
