### ISSUE TITLE
update to 34.0.4

### ISSUE THREAD

**Issue by 2011** [nmeum/android-tools#122]
This page has version 34.0.4 of the tools (compiled):

https://developer.android.com/studio/releases/platform-tools

Can you update android-tools?

**Comment by Biswa96** [comment]
It is already updated, just not tagged or released yet in this repository.

**Comment by anatol** [comment]
@nmeum can you tag it?

Or maybe @Biswa96 you can do it?

**Comment by Biswa96** [comment]
In release page, is the tarball attached from CI artifact?

**Comment by Biswa96** [comment]
I have attached the tarball from CI artifact.

34.0.4 tag is released https://github.com/nmeum/android-tools/releases/tag/34.0.4

**Comment by nmeum** [comment]
Looks good. Thank you!
