### ISSUE TITLE
Double tap [Tab] freezes terminals

### ISSUE THREAD

**Issue by youngunix** [nmeum/android-tools#123]
Hello, 

background:

- OS: Gentoo (stable, latest).
- Android-tools: v34.0.0
- terminals used: terminator & xfce-terminal.
- shell: zsh.

I just installed the android-tools from the main Gentoo repo, this package never existed on my system before. When I type `adb` in the terminals above, then double tap [Tab] for completion, the terminals freeze and I have to force close them. Not sure if this is a terminal, shell, or `adb` issue. let me know if you need any log to help troubleshoot this issue.

**Comment by Biswa96** [comment]
Do you mean something like shell completions? The upstream repositories only provide bash completions for adb and fastboot. For zsh, oh-my-zsh project has shell completion file for adb, see https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/adb/_adb

**Comment by youngunix** [comment]
@Biswa96 thank you for pointing me to the right direction. I was able to solve this issue by enabling the `adb` plugin in `~/.zshrc`.
