### ISSUE TITLE
Interest in Snap packaging?

### ISSUE THREAD

**Issue by fredldotme** [nmeum/android-tools#140]
Hello!

I'm in the process of creating a packaging recipe suitable for building Snaps, for use in constrained environments like Ubuntu Touch and Ubuntu Core (Desktop).

Snap packaging allows to fetch CLI tools into environments where the host OS is naturally limited in the abilities to damage it, like Ubuntu Core or (shameless self-plug) Ubuntu Touch, with a permission system that still enables full functionality.

Are you interested in having this packaging YAML recipe contributed? Otherwise I would release it myself (with varying degrees of maintainership).

Disclaimer: I would prefer this not to turn into a Flatpak-vs-AppImage-vs-Snap sh*t flinging fest (I'm too old for that), but I am willing to provide upstream with the option to have official packaging that can be easily fetched by everyone willing to use Snaps on their development boxes.

Thank you!

**Comment by Biswa96** [comment]
Please feel free to create a pull request. I am not familiar with Snap packaging but I would welcome the addition. Others may help on the Snap topic.

**Comment by anatol** [comment]
+1 to what @Biswa96  said. I am fine with having a snap file if it is something to be used by our users. But don't think anyone from the core team has experience with snaps, so somebody (e.g. @fredldotme) needs to support it.

**Comment by fredldotme** [comment]
Thank you. As long as I'm not completely doing this by myself I'm happy to help.

PR is here: https://github.com/nmeum/android-tools/pull/141

**Comment by fredldotme** [comment]
Update from my side: I have asked for a name transfer for the name `android-tools` from the Snap Store team, meaning I would be able to transfer it to either one of you maintaining this source repo (for the blue checkmark) or keep it myself should you back out. I will keep you updated here.

**Comment by fredldotme** [comment]
Not to be rude but I sense some "chickening out" in the room
