### ISSUE TITLE
[enhancement request] Install flag for documents

### ISSUE THREAD

**Issue by Piscium** [nmeum/android-tools#146]
The released tar file contains two markdown documents in folder "vendor/adb/docs/user/", one of which is the adb man page which is quite useful.

Would it be possible to add an install flag for these documents?

**Comment by Biswa96** [comment]
I have added a pull request to install adb man page generated by pandoc. Would you like to review the pull request please?

**Comment by Piscium** [comment]
Thanks, Biswa96.
