### ISSUE TITLE
adb connect not working

### ISSUE THREAD

**Issue by hrap1919** [nmeum/android-tools#15]
The issue is an over-patching in core/0026-adb-disable-mDNS.patch/adb/socket_spec.cpp preventing any outer tcp-connection.

Even if we remove mDNS, the patched place in socket_spec.cpp MUST contain the code
````
 if (tcp_host_is_local(hostname)) {
            fd->reset(network_loopback_client(port_value, SOCK_STREAM, error));
        } else {
            fd->reset(network_connect(hostname, port_value, SOCK_STREAM, 0, error));
        }
````
The current release has no the "else" part

**Comment by nmeum** [comment]
Good catch, thanks! Should be fixed now.
