### ISSUE TITLE
Build failure with gcc 11

### ISSUE THREAD

**Issue by nmeum** [nmeum/android-tools#16]
With the (yet to be released) GCC 11 compilation of boringssl fails (for instance on Fedora 34) with the following error message:

```
In file included from /home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/bcm.c:38:
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/bn/asm/x86_64-gcc.c:427:51: error: argument 2 of type ‘const uint64_t[8]’ {aka ‘const long unsigned int[8]’} with mismatched bound [-Werror=array-parameter=]
  427 | void bn_sqr_comba8(BN_ULONG r[16], const BN_ULONG a[8]) {
      |                                    ~~~~~~~~~~~~~~~^~~~
In file included from /home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/bn/add.c:64,
                 from /home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/bcm.c:37:
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/bn/internal.h:292:51: note: previously declared as ‘const uint64_t[4]’ {aka ‘const long unsigned int[4]’}
  292 | void bn_sqr_comba8(BN_ULONG r[16], const BN_ULONG a[4]);
      |                                    ~~~~~~~~~~~~~~~^~~~
In file included from /home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/bcm.c:100:
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/sha/sha256.c: In function ‘SHA224_Final’:
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/sha/sha256.c:122:10: error: ‘SHA256_Final’ accessing 32 bytes in a region of size 28 [-Werror=stringop-overflow=]
  122 |   return SHA256_Final(out, ctx);
      |          ^~~~~~~~~~~~~~~~~~~~~~
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/sha/sha256.c:122:10: note: referencing argument 1 of type ‘uint8_t *’ {aka ‘unsigned char *’}
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/sha/sha256.c:172:20: note: in a call to function ‘SHA256_Final’
  172 | #define HASH_FINAL SHA256_Final
      |                    ^~~~~~~~~~~~
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/sha/../digest/md32_common.h:231:5: note: in expansion of macro ‘HASH_FINAL’
  231 | int HASH_FINAL(uint8_t out[HASH_DIGEST_LENGTH], HASH_CTX *c) {
      |     ^~~~~~~~~~
In file included from /home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/bcm.c:101:
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/sha/sha512.c: In function ‘SHA384_Final’:
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/sha/sha512.c:137:10: error: ‘SHA512_Final’ accessing 64 bytes in a region of size 48 [-Werror=stringop-overflow=]
  137 |   return SHA512_Final(out, sha);
      |          ^~~~~~~~~~~~~~~~~~~~~~
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/sha/sha512.c:137:10: note: referencing argument 1 of type ‘uint8_t *’ {aka ‘unsigned char *’}
/home/nmeum/android-tools/vendor/boringssl/crypto/fipsmodule/sha/sha512.c:196:5: note: in a call to function ‘SHA512_Final’
  196 | int SHA512_Final(uint8_t out[SHA512_DIGEST_LENGTH], SHA512_CTX *sha) {
      |     ^~~~~~~~~~~~
cc1: all warnings being treated as errors
```

This does not seem to be specific to this repository though as the same build failure occurs with [boringssl]( https://github.com/google/boringssl) git HEAD (6b48efac7b3b229c17cff55e5cfd9f9a0aea9b70). Regarding the specific warnings: The first seems to be mismatch between function prototype and function implementation. The second seems to be an array size mismatch which doesn't seem to be a real issue though as the passed `HASH_CTX` contains the amount of bytes which should actually be accessed. I think it would be best to report this to boringssl upstream. Unfortunately, their issue tracker requires a google account and I don't have one and don't plan on creating one.

**Comment by vanaf** [comment]
Created https://bugs.chromium.org/p/boringssl/issues/detail?id=402

Going to create patch for vendor/boringssl/CMakeLists.txt to remove `-Werror` from there

**Comment by david-geiger** [comment]
Hi,

First a big thanks for this "Unoffical CMake-based build system" project, it is now more easier to package android-tools to a Linux distribution.
I have started to use it now for our distribution Mageia Linux:

http://svnweb.mageia.org/packages?view=revision&revision=1721129

It build fine on our stable release (Mageia 8) using GCC 10 but same build issue on Mageia Cauldron (development release) using GCC 11 compiler.


Regards,
David

**Comment by david-geiger** [comment]
So here the following three patches fixes GCC 11 build issue:

http://svnweb.mageia.org/packages?view=revision&revision=1721331

**Comment by anatol** [comment]
Thanks @david-geiger. Could you please send these patches as a pull request here?

**Comment by vanaf** [comment]
I'am going to create it, I had google provided 2 applied successfully third one not yet.
