### ISSUE TITLE
How to cross compile adb with ndk

### ISSUE THREAD

**Issue by mengyanshou** [nmeum/android-tools#161]
How to cross compile adb with ndk, any help, thanks!

**Comment by Biswa96** [comment]
Are you trying to use adb in Android?

**Comment by mengyanshou** [comment]
I was able to successfully compile adb for linux in the arm64, but when I executed it in Android termux, only the Bad System Call was returned

this repo https://github.com/Magisk-Modules-Repo/adb-ndk can use static adb binary, but i want modify source code to compile new adb binary

**Comment by Biswa96** [comment]
> but when I executed it in Android termux, only the Bad System Call was returned

Try to find the system call in logcat output. termux uses many patches on top of this repository. Those patches can be found here https://github.com/termux/termux-packages/tree/master/packages/android-tools.

**Comment by Biswa96** [comment]
There is no set_robust_list(2) call in android-tools repository including git submodules. It is probably coming from other dependencies.
