### ISSUE TITLE
Add support for LoongArch64

### ISSUE THREAD

**Issue by 13584452567** [nmeum/android-tools#164]
After applied this [patch](https://github.com/google/boringssl/pull/31)，it can be compiled successufully on loong64 platform.I don't know how to pull this path to this repo.If you can help me do this ,thank you very much

![376438677-5674727b-6eb4-424d-9a62-95fce3d38343](https://github.com/user-attachments/assets/d04e6592-e21b-4953-b075-07186680b78f)

**Comment by Biswa96** [comment]
We could continue the discussion in the previous thread. But anyway, I have not seen any publicly available loongarch hardware which could help to test the patch file. I am not sure if the patch file should be added blindly.

**Comment by 13584452567** [comment]
ASUS announced their XC-LS3A6M and im using this product to test loong64-abi2.0
now,it seems works well.

**Comment by Biswa96** [comment]
The patch file should be added in patches/boringssl directory. It should be in proper git patch format.

**Comment by Biswa96** [comment]
You could create a pull request with the patch file and wait for maintainers to merge it.

**Comment by 13584452567** [comment]
> You could create a pull request with the patch file and wait for maintainers to merge it.

I have opened [PR](https://github.com/nmeum/android-tools/pull/165)

Thank you very much!

**Comment by Biswa96** [comment]
Fixed in above PR.
