### ISSUE TITLE
undefined reference to symbol '_ZN4absl12lts_2024072212log_internal17MakeCheckOpStringIllEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_T0_PKc'

### ISSUE THREAD

**Issue by PurpleVsGreen** [nmeum/android-tools#168]
Ohayo!

I do this:
```
git clone 'https://github.com/nmeum/android-tools.git'
cd android-tools
git submodule update --init
git config user.name 'What Zit Tooya'
git config user.email 'what@zit.tooya'
for each in .git/modules/vendor/*/config .git/modules/*/config; do grep -A2 -e '^.user.$' .git/config >> $each; done
mkdir build
cd build
cmake -DANDROID_TOOLS_USE_BUNDLED_FMT=ON -DANDROID_TOOLS_USE_BUNDLED_LIBUSB=ON ..
gmake --jobs=$(nproc)
```

I get this:
```
...
[ 64%] Linking CXX executable adb
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: liblibadb.a(adb_host.pb.cc.o): undefined reference to symbol '_ZN4absl12lts_2024072212log_internal17MakeCheckOpStringIllEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_T0_PKc'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libabsl_log_internal_check_op.so.2407.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [vendor/CMakeFiles/adb.dir/build.make:386: vendor/adb] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:734: vendor/CMakeFiles/adb.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

Happens on Gentoo on amd64. All the dependencies are merged.

I'm probably doing it wrong and humbly apologize if that's the case here.
If you need any further information I'd be happy to share.

Have a nice day :)

**Comment by Biswa96** [comment]
I can not reproduce the issue in ArchLinux with abseil-cpp version 20240722.0. Please make sure to rebuild all the reverse dependencies of abseil-cpp. Also, delete the build directory of android-tools before trying to rebuild it.

**Comment by PurpleVsGreen** [comment]
I see your WFM and raise you my FTBFS. I can reproduce the issue 100% of the time, have rebuilt the entire dependency chain and completely started over several times already, but the error persists.

The only other reverse dependency of abseil-cpp is protobuf, which I've also rebuilt.

In addition to that, I've rebuilt the C++ dependencies with both -DCMAKE_CXX_STANDARD=14 and -DCMAKE_CXX_STANDARD=17, didn't work. I added -DBUILD_SHARED_LIBS=ON to dev-cpp/abseil-cpp, also didn't work.

The missing reference is the same one every time.

Do you have any other ideas, please?

**Comment by Biswa96** [comment]
I'm not familiar with gentoo. Could you reproduce the issue in a Linux distribution which are used in CI build?
