### ISSUE TITLE
Binaries in "vendor" folder

### ISSUE THREAD

**Issue by ollieparanoid** [nmeum/android-tools#2]
There are a lot of binaries and source code tarballs in the "vendor" folder. The idea is to build everything from source as I understand, so the binaries are not useful. Also they increase the download size quite a bit, the whole vendor folder of the latest release is over 400 MB in size.

**Comment by nmeum** [comment]
I also consider this to be a problem. The interesting question is how to approach it, after all these are not binary files generated by us but binaries files included in the android repositories, e.g. `extras/ioshark/wl.tar`.

We could either manually remove certain files (blacklisting) or we could only ship the files we need for compiling the binaries (whitelisting). Not sure if CPack has support for the latter.

**Comment by nmeum** [comment]
I was hoping that CPack (the CMake thingy used to create the source tarball) has some kind of builtin functionality to extract source files from the CMake target definitions. If that's the case there is no need for a custom script. Unfortunately, this doesn't seem to be the case.

**Comment by nmeum** [comment]
I "fixed" this simply by ignoring more files using the `CPACK_SOURCE_IGNORE_FILES` CMake variable. The tarball is now ~150MB smaller and it still seems to build.

Unless you have any further comments on this I would suggest closing this issue.

**Comment by ollieparanoid** [comment]
Excellent!
