### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by nmeum** [nmeum/android-tools#21]
I would like to add a license to this repository. I believe this to be useful for downstream Linux distributions, with some even requiring OSI/FSF approved licenses. I would suggest simply using Apache-2.0 since that's what Android itself uses. The problem is: I am not the only one how contributed code to this repository so my naive legal understanding is that I cannot just go ahead and commit a license file. The following people have committed code to this repository:

* [x] @Minecrell 
* [x] @Johnnynator 
* [x] @sgn 
* [x] @anatol

Would you mind licensing this repository under Apache-2.0? Any suggestions on how to best record this consent as part of the commit history?

**Comment by Johnnynator** [comment]
I'm fine with re-licensing. Don't know how to best record the consent.

**Comment by anatol** [comment]
Feel free to relicense my changes to Apache 2.0

> Any suggestions on how to best record this consent as part of the commit history?

Once everyone agreed with the license change - commit the LICENSE file with a reference to this ticket ("Closes #21"). And CC all the contributors to the git commit.

**Comment by sgn** [comment]
Acked-by: Đoàn Trần Công Danh <congdanhqx@gmail.com>

**Comment by sgn** [comment]
I think for the record, each person could make a signed commit to a re-license agreement and merge to main repository?

**Comment by Minecrell** [comment]
> Would you mind licensing this repository under Apache-2.0? 

Sounds good to me :)

**Comment by nmeum** [comment]
Done, thanks!

**Comment by anatol** [comment]
Thanks!

This license file needs to be installed by CMake. That's in addition to the upstream AOSP license.
