### ISSUE TITLE
mke2fs exit with status 1 during fastboot format userdata on Fedora 34

### ISSUE THREAD

**Issue by leo-lb** [nmeum/android-tools#25]
Hello!

```
# fastboot format userdata
/usr/bin/mke2fs failed with status 1
fastboot: error: Cannot generate image for userdata
# which mke2fs
/usr/sbin/mke2fs
```

It seems it uses the wrong path, in bin instead of sbin.

Here is the source for the Fedora package: https://src.fedoraproject.org/rpms/android-tools/blob/rawhide/f/android-tools.spec

Thank you!

**Comment by leo-lb** [comment]
When symlinking, it still fails:

```
# ln -s /usr/sbin/mke2fs /usr/bin/mke2fs
# fastboot format userdata
mke2fs 1.45.6 (20-Mar-2020)
/tmp/TemporaryFile-LVZNu2: Unimplemented ext2 library function while setting up superblock
/usr/bin/mke2fs failed with status 1
fastboot: error: Cannot generate image for userdata
```

**Comment by vanaf** [comment]
Which version of android-tools do you use?

By default Fedora 34 comes with android-tools-20180828gitc7815d675-8.fc33.x86_64 which is not handled by this project.

**Comment by leo-lb** [comment]
@vanaf I use that one version, you're right sorry the latest on f33 branch wasnt pushed to Fedora yet.
