### ISSUE TITLE
The disconnected/rebootable device does not disconnect and remains in the active list (no control of the "offline" status)

### ISSUE THREAD

**Issue by AKotov-dev** [nmeum/android-tools#28]
Hello. Thank you very much for your work, it is very necessary and useful. I really need your advice on the following issue...  
I'm testing `android-tools v31.0.0p1` on emulators vv5.1/9.0 from: https://osdn.net/projects/android-x86/releases

> adb connect 192.168.0.80
connected to 192.168.0.80:5555
> adb devices
List of devices attached
192.168.0.80:5555	device

> adb shell reboot -p
... and here it continues to hang, and meanwhile the device is already turned off and, accordingly, does not accept any commands.

Tracking the `offline` status does not work when the device is rebooted or disconnected. Let me remind you that the normal shutdown/reboot of the device takes place in several stages...

For example - normal Shutdown:
--
1. command:  `adb shell reboot -p`
2. Turning off the device
3. The adb server shows the status "offline" (`adb devices`)
4. **After 1-2 minutes, the device that is already turned off leaves the list of connected devices**

In versions 29.0.6, 30.0.5p1 & 31.0.0p1 (I didn't check the others) the disconnected device is permanently connected even after it is disconnected. Is this a bug?

I can't test it on a real device, there is no smartphone.
I apologize for my poor English, I communicate through an online translator.

p.s. for easy and quick control of the device behavior, you can use my `ADBManager`: https://github.com/AKotov-dev/adbmanager if compatible for you. It is under development, but it will speed up the process of testing android-tools in general.

Sincerely,
Alex

**Comment by vanaf** [comment]
I believe it is due to long tcp timeouts. Same behaviour you can see with ssh if you forcely reboot the target.
The question is why adbd on device don't correctly close the connection (or we don't listen to it)
Do you see expected behaviour with any other version of adb (e.g. shipped by google)?

**Comment by AKotov-dev** [comment]
The problem with the tcp timeout disappears, because the device hangs in the "connected" constantly. I am using Mageia Linux-8. At the moment, this distribution uses android-tools-10.0.0_r2-3.mgu8.x86_64.rpm, which has no problems with determining the "offline" status when disconnected or rebooted. I will give a link to src.rpm to understand what source codes we are talking about: https://distrib-coffee.ipsl.jussieu.fr/pub/linux/Mageia/distrib/8/SRPMS/core/release/android-tools-10.0.0_r2-3.mga8.src.rpm

**Comment by AKotov-dev** [comment]
Hello. I downloaded the archive of the updated version SDK Platform-Tools `v31.0.2 (April 2021)` from here: https://developer.android.com/studio/releases/platform-tools#downloads and replaced the file /usr/bin/adb per file "adb" from this archive.

> adb version
Android Debug Bridge version 1.0.41
Version 31.0.2-7242960
Installed as /usr/bin/adb

Now everything works great! :)

**Based on the version change history the bug was fixed starting with the version v31.0.1:**
31.0.1 (March 2021)
adb
**Reduce TCP keepalive interval**
...

Can you update your version of android-tools to the latest, i.e. to v31.0.2 (April 2021)?

Thank you in advance,
Alex
