### ISSUE TITLE
Update to Android 9

### ISSUE THREAD

**Issue by ollieparanoid** [nmeum/android-tools#3]
I am not sure if there are relevant changes, but to keep up with upstream it would probably make sense to rebase this on the latest Android version, right?

Possibly related: [ADB sideloading doesn't work](https://gitlab.com/postmarketOS/pmbootstrap/issues/1638) anymore in Alpine chroots, but it does work with the host system's fastboot version.

**Comment by nmeum** [comment]
> […] it would probably make sense to rebase this on the latest Android version, right?

Indeed, I started working on this, will take some time though.

> Possibly related: ADB sideloading doesn't work anymore in Alpine chroots, but it does work with the host system's fastboot version.

Did this ever work before? If so: With which version?

**Comment by ollieparanoid** [comment]
> Indeed. I started working on this, will take some time though.

Thanks!

> Did this ever work before? If so: With which version?

It worked at least in [August 2017](https://github.com/postmarketOS/pmbootstrap/pull/404#issuecomment-324406091), at which time it was `5.1.1_p13` in the Alpine repos.

**Comment by nmeum** [comment]
> It worked at least in August 2017, at which time it was 5.1.1_p13 in the Alpine repos.

Could you open a separate issue for this? I would like to do a new release shortly for android 9 (thereby closing this issue) and address this and #2 later on.

**Comment by ollieparanoid** [comment]
Sure! Split into #4 :+1:

**Comment by nmeum** [comment]
> Sure! Split into #4 :+1:

Thanks.

---

I also made a [new release for android 9.0.0_r3](https://github.com/nmeum/android-tools/releases/tag/9.0.0_r3). Additionally, I am currently preparing [an upgrade of the Alpine Linux package]( https://github.com/alpinelinux/aports/pull/5203) which I will merge soonish if everything works as expected.

I am therefore closing this issue.
