### ISSUE TITLE
Use Github Actions for (test) builds

### ISSUE THREAD

**Issue by munix9** [nmeum/android-tools#31]
Maybe it would be useful to use Github Actions for (test) builds.
I have already tested this for openSUSE Tumbleweed:
https://github.com/munix9/android-tools/tree/master-actions/.github/workflows
https://github.com/munix9/android-tools/tree/platform-tools-31_0_2-actions/.github/workflows

This is certainly expandable, also for other distris. It could also be used to build a new release and the corresponding package.

The handling of Github Actions with different branches is currently a bit tedious (default-branch must be changed accordingly).

**Comment by nmeum** [comment]
Yes CI would be very nice, I am personally just not familiar with Github Actions and didn't get around to looking into them yet. If you have something ready just send a PR :)

**Comment by nmeum** [comment]
Done in #42
