### ISSUE TITLE
Add some other tools

### ISSUE THREAD

**Issue by Lzhiyong** [nmeum/android-tools#39]
Can you add some other tools like aapt2 aidl and so on, because I also made one like yours, [sdk-tools](https://github.com/Lzhiyong/sdk-tools) including build-tools and platform-tools, but I think you do better

**Comment by Biswa96** [comment]
@nmeum Can I add other tools as OP asked?

**Comment by Atemu** [comment]
Hi, why was this closed?

**Comment by Biswa96** [comment]
Which tool do you need? Other tools are hard to build/maintain or require more dependencies.

**Comment by Atemu** [comment]
As the OP mentions, build-tools such as aapt2 and the like.

**Comment by Biswa96** [comment]
If things do not require Java I can try to work on that. But maintainer's approval is necessary first.

**Comment by anatol** [comment]
@Biswa96 what binaries do you plan to add and how much it complicates the build script?

I am fine with adding the new tools as long as there is someone who maintains its build system. cc @nmeum
