### ISSUE TITLE
ADB sideloading is broken

### ISSUE THREAD

**Issue by ollieparanoid** [nmeum/android-tools#4]
Split up from #3:
>>> ADB sideloading doesn't work anymore in Alpine chroots, but it does work with the host system's fastboot version.
>>
>> Did this ever work before? If so: With which version?
>
> It worked at least in [August 2017](https://github.com/postmarketOS/pmbootstrap/pull/404#issuecomment-324406091), at which time it was `5.1.1_p13` in the Alpine repos.

Downstream bug report (postmarketOS):
https://gitlab.com/postmarketOS/pmbootstrap/issues/1638

EDIT: I have also reproduced this myself.

**Comment by ollieparanoid** [comment]
FWIW the bug still exists. Here's the output and log file:
```
$ adb -P 5038 wait-for-usb-sideload
* daemon not running; starting now at tcp:5038
ADB server didn't ACK
Full server startup log: /tmp/adb.0.log
Server had pid: 16558
--- adb starting (pid 16558) ---
adb I 10-24 07:01:30 16558 16558 main.cpp:56] Android Debug Bridge version 1.0.40
adb I 10-24 07:01:30 16558 16558 main.cpp:56] Version ADB_VERSION
adb I 10-24 07:01:30 16558 16558 main.cpp:56] Installed as /usr/bin/adb
adb I 10-24 07:01:30 16558 16558 main.cpp:56] 
adb I 10-24 07:01:30 16558 16558 adb_auth_host.cpp:421] adb_auth_init...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

* failed to start daemon
error: cannot connect to daemon
```

```
$ sudo cat /tmp/adb.0.log
--- adb starting (pid 16611) ---
adb I 10-24 07:03:31 16611 16611 main.cpp:56] Android Debug Bridge version 1.0.40
adb I 10-24 07:03:31 16611 16611 main.cpp:56] Version ADB_VERSION
adb I 10-24 07:03:31 16611 16611 main.cpp:56] Installed as /usr/bin/adb
adb I 10-24 07:03:31 16611 16611 main.cpp:56] 
adb I 10-24 07:03:31 16611 16611 adb_auth_host.cpp:421] adb_auth_init...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

I guess this might be musl related?

**Comment by ollieparanoid** [comment]
(This might mean that adb is broken in general, I did not look further into it.)

**Comment by nmeum** [comment]
Hm, I can't reproduce that `adb wait-for-usb-sideload` error on Alpine Linux Edge with my android 7.1.2 phone running Lineage OS 14. Could you elaborate further which steps are necessary to reproduce this?

adb itself shouldn't be broken. I used it various times in the past to update my phone using `adb sideload`.

Did you run adb as root?

**Comment by ollieparanoid** [comment]
@nmeum, thank you for trying to reproduce this!

@Decatf [figured out](https://gitlab.com/postmarketOS/pmbootstrap/issues/1638#note_111470968) why the crash happens:
> The adb server uses the HOME env variable [1]. It tries to get that var and has a fallback to retrieving the home path programmatically. The pmbootstrap chroot call doesn't set HOME so the fallback code is taken. This crash is gone when the HOME var is set.
> ...
> [1] https://android.googlesource.com/platform/system/core/+/android-9.0.0_r3/adb/adb_utils.cpp#245

I can confirm that it works as intended when setting HOME and I'm patching pmbootstrap to do that by default. His patch in #5 seems to fix it, even if HOME is not set, so I'm leaving this issue open.
