### ISSUE TITLE
Does fastboot still require libpcre?

### ISSUE THREAD

**Issue by mid-kid** [nmeum/android-tools#41]
What it says on the tin. It seems to link and function fine without `pcre2-8` in the target_include_libraries.

**Comment by mid-kid** [comment]
Same with `fmt::fmt`. I don't even have that installed.

**Comment by Johnnynator** [comment]
`pcre2` is used by `selinux/libselinux/src/regex.{c,h}`, but all includes of `regex.h` that are used in this subset, are mostly no-op-ish, but maintaining a patch set to keep this clean is probably more work, than just requiring it at compile time.

The `fmt::fmt` seems to actually not be used anymore in any of our used code parts, so it should be safe to drop.

**Comment by mid-kid** [comment]
I see. Then libpcre is just a build-time dep, just like gtest. I wonder if providing a mock header would work as well, here.

**Comment by sgn** [comment]
Isn't `fmt::fmt` used in `core/fastboot/vendor_boot_img_utils.cpp`?

**Comment by nmeum** [comment]
`vendor/libbase/include/android-base/format.h` should also require libfmt. I think neither pcre2 nor libfmt can be removed. I don't think mocking headers are worth the effort.

**Comment by mid-kid** [comment]
But libfmt isn't even installed and it builds/runs fine...

**Comment by nmeum** [comment]
Which version of android-tools are you referring to? Git HEAD?

**Comment by mid-kid** [comment]
I was referring to the latest github release, but thanks, good to know.

**Comment by nmeum** [comment]
Ah, the fmt dependency is about to be introduced with the upcoming platform-tools-31.0.2 release. Next time just mention which version you are referring to :)

**Comment by mid-kid** [comment]
For some reason I'm building 31.0.2 without libfmt without issues still...

**Comment by nmeum** [comment]
Yes, because it is vendored, see #40.
