### ISSUE TITLE
Build fails in 31.0.3 in Musl target.

### ISSUE THREAD

**Issue by marcel0alves** [nmeum/android-tools#53]
When I'm trying building in Gentoo Linux with Musl and Clang, I got this message: 

```
In file included from /var/tmp/portage/portage/dev-util/android-tools-31.0.3/work/android-tools-31.0.3/vendor/e2fsprogs/contrib/android/e2fsdroid.c:8:

/var/tmp/portage/portage/dev-util/android-tools-31.0.3/work/android-tools-31.0.3/vendor/e2fsprogs/lib/ext2fs/ext2fs.h:1378:39: error: unknown type name 'dev_t'; did you mean 'div_t'?
extern char *ext2fs_find_block_device(dev_t device);
                                      ^~~~~
                                      div_t
/usr/include/stdlib.h:62:35: note: 'div_t' declared here
typedef struct { int quot, rem; } div_t;
                                  ^
In file included from /var/tmp/portage/portage/dev-util/android-tools-31.0.3/work/android-tools-31.0.3/vendor/e2fsprogs/contrib/android/e2fsdroid.c:8:
/var/tmp/portage/portage/dev-util/android-tools-31.0.3/work/android-tools-31.0.3/vendor/e2fsprogs/lib/ext2fs/ext2fs.h:1785:62: error: unknown type name 'mode_t'
```

This occurs because Musl have sys/types.h, but apparently doesn't declare HAVE_SYS_TYPES_H, so I set -DHAVE_SYS_TYPES_H=1 and build fine.

**Comment by nmeum** [comment]
903aa02f24c238b59605be344372c5c8a4e5c2f6 builds fine for me on Alpine Linux Edge and also passed on the CI. Quickly looking at the code, the `HAVE_SYS_TYPES_H` feature test macro should be set unconditionally from `config.h`  [\[1\]](https://android.googlesource.com/platform/external/e2fsprogs/+/refs/tags/platform-tools-31.0.3/util/android_config.h#35) [\[2\]](https://android.googlesource.com/platform/external/e2fsprogs/+/refs/tags/platform-tools-31.0.3/util/gen-android-files#50). `contrib/android/e2fsdroid.c` should include this header indirectly via `contrib/android/perms.h`.

**Comment by marcel0alves** [comment]
In Gentoo Linux I can define this via `package.env`:

```
~ $ cat /etc/portage/env/have-sys-types-h
CFLAGS="${CFLAGS} -DHAVE_SYS_TYPES_H=1"
CXXFLAGS="${CFLAGS}"
```
```
~ $ grep have-sys /etc/portage/package.env
dev-util/android-tools have-sys-types-h
```

If you can build fine on Alpine Linux, I really don't know how this occurs on Gentoo.

**Comment by nmeum** [comment]
Would still be nice to figure out why this is failing on Gentoo. Ideally, this code should build fine without any patches on musl Gentoo :)

**Comment by Johnnynator** [comment]
We do not even build/use `e2fsdroid.c` (yet). This is done by the Gentoo patchset atop of android-tools.

https://dev.gentoo.org/~zmedico/dist/android-tools-31.0.0_p1-install-e2fsdroid-ext2simg.patch

**Comment by mid-kid** [comment]
@marcel0alves Please consider reporting build-time failures on the gentoo bugtracker first, before going upstream with them. Apparently it had already been reported: https://bugs.gentoo.org/829152
