### ISSUE TITLE
33.0.1 release

### ISSUE THREAD

**Issue by anatol** [nmeum/android-tools#62]
Android devs finally pushed platform-tools-33.0.1 to the repo (https://issuetracker.google.com/issues/229569602). It makes `android-tools` update to 33.0.1 release possible.

**Comment by jershell** [comment]
I checkout on 33.0.1 tag and i fixed patches. Now I have a success build. I don't know how I can to check errors. https://github.com/nmeum/android-tools/pull/65

**Comment by anatol** [comment]
https://github.com/nmeum/android-tools/commit/078c6517eb40933140304ad0c23f16bafcb68095
