### ISSUE TITLE
Armhf package ?

### ISSUE THREAD

**Issue by a1ex4** [nmeum/android-tools#7]
Hey, thank you for creating this repository.

I just upgraded one of my Docker container running Alpine and I realized there is no way I can install android-tools on my Raspberry pi... I understand supporting other arch is not in sight but could I find a armhf package anywhere ? I tried searching everywhere but without luck, are there any archives or anything else where I could find the package ?
Thank you so much in advance! 🙂

**Comment by nmeum** [comment]
An armhf package for Alpine Linux? That's being worked on currently. See #6 and https://github.com/alpinelinux/aports/pull/5681. Unfortunately, I don't own armhf hardware and the person who created https://github.com/alpinelinux/aports/pull/5681 didn't respond so far which is why there is no android-tools package on Alpine for armhf currently. Maybe you could help out?

**Comment by ollieparanoid** [comment]
This was fixed in https://github.com/alpinelinux/aports/commit/67283cdbf6ef0ce2912bd28297714d6bb3976a38, the issue can be closed :+1:

**Comment by nmeum** [comment]
This only fixes the build on alpine linux. I would also like to commit a fix to this repository so adjusting the CFLAGS downstream is no longer necessary.

**Comment by nmeum** [comment]
With the upgrade to platform-tools-29.0.3 android-tools is build with `-Wno-attributes` by default.

https://github.com/nmeum/android-tools/blob/db84fde9f61120d91c12e8ee2eb4169e16dea919/vendor/CMakeLists.txt#L36-L37

Additionally, boringssl is included with `EXCLUDE_FROM_ALL` thus I believe that the test program, previously causing this build failure on ARM, is no longer build.

https://github.com/nmeum/android-tools/blob/db84fde9f61120d91c12e8ee2eb4169e16dea919/vendor/CMakeLists.txt#L4

I verified that android-tools currently builds without any CFLAG changes on Alpine ARM and therefore consider this issue fixed.
