### ISSUE TITLE
adding d8?

### ISSUE THREAD

**Issue by Mis012** [nmeum/android-tools#72]
how hard would it be to add d8? the upstream project requires depot-tools, which is quite sad...

**Comment by theoparis** [comment]
+1 for not needing the depot tools dependency. 
I would also like to see `dx` added.

**Comment by Mis012** [comment]
dx is not that painful to build, we have it as part of https://gitlab.com/android_translation_layer/art_standalone

**Comment by Biswa96** [comment]
This project is to provide platform-tools https://developer.android.com/tools/releases/platform-tools and not for build tools for Android application.

**Comment by Mis012** [comment]
I guess looking at it again I'm pretty sure none of the currently supported tools are anywhere near as hostile to packaging attempts as d8, not sure if I maybe intended to post this issue on some other similar project, the fact that when I read @theoparis's comment I was almost sure dx is already packaged by this project would certainly speak for that...
